version: "3"

services:
  php-fpm:
    container_name: php-fpm
    build:
      context: docker/php-fpm
    volumes:
      - ./:/var/www/html
      - ./docker/php-fpm/www.conf:/etc/php8/php-fpm.d/www.conf:ro
      - ./docker/php-fpm/php.ini:/usr/local/etc/php/php.ini

  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/sites/:/etc/nginx/sites-available
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d
    depends_on:
      - php-fpm
    ports:
      - "8080:80"
    links:
      - php-fpm