name: Actions
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: appleboy/ssh-action@master
        with:
          host: "ec2-3-141-193-53.us-east-2.compute.amazonaws.com"
          key: "AKIA6ITFMYUANKSVSM6J"
          username: ubuntu

          script: |
            cd /var/www/ci-cd/
            git pull
